name: Docker Image CI

on:
  push:
    tags: 
     - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set release version var
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build tpm Docker image
      run: cd tpm && docker build . --file Dockerfile --tag tpm2-simulator:${{ env.RELEASE_VERSION }}
